Avoid redefinition of the cr-toolbar name for bookmarks page
Upstream re-introduced a cr_toolbar.js import in bookmarks/toolbar.ts,
which collides with our br_toolbar.m.js, which also defines cr-toolbar,
causing a Javascript error when opening the bookmarks page like this:

  Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry':
  the name "cr-toolbar" has already been used with this registry",
  source: chrome://bookmarks/ (0)

Remove that import to get the bookmarks page working again.

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/